name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed

jobs:
  e2e-tests:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pinspire_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./app/backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./app/frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./app/frontend
        env:
          CI: true

      - name: Copy frontend build to backend
        run: npm run build:ui

      - name: Start backend server
        run: npm run start:test &
        working-directory: ./app/backend
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/pinspire_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-jwt-secret

      - name: Install Playwright dependencies
        run: |
          npm ci
          npx playwright install --with-deps
        working-directory: ./app/e2e-tests

      - name: Run E2E tests
        run: npm run test
        working-directory: ./app/e2e-tests
