name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "app/frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "app/frontend/**"

jobs:
  frontend_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./app/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./app/frontend/package-lock.json"

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run component tests
        run: npm test
        env:
          CI: true

      - name: Build frontend
        run: npm run build
        env:
          CI: true
