services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # networks:
    #   - app-network

  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - redis
  #   networks:
  #     - app-network

volumes:
  redis_data:
# networks:
#   app-network:
#     driver: bridge
